res = input('Digite algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(res)))
print('Só tem espaços? {}'.format(res.isspace()))
print('É um número? {}'.format(res.isnumeric()))
print('É alfabético? {}'.format(res.isalpha()))
print('É alfanumérico? {}'.format(res.isalnum()))
print('Está em maiúsculas? {}'.format(res.isupper()))
print('Está em minúsculas? {}'.format(res.islower()))
print('Está capitalizada? {}'.format(res.istitle()))